application: willnetwillnet
version: 1
runtime: python
api_version: 1
handlers:
- url: /
  static_files: index.html
  upload: index.html
- url: /images
  static_dir: images
- url: /css
  static_dir: css
- url: /(.*\.py)
  script: \1
- url: /(.*)
  static_files: \1
  upload: /(.*)
- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico
  mime_type: image/x-icon


